# Generated by Django 5.2 on 2025-04-26 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('subject_text', models.CharField(max_length=255)),
                ('decision_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_accusative', models.CharField(max_length=255)),
                ('surname_in_accusative', models.CharField(max_length=255)),
                ('father_name_in_genitive', models.CharField(max_length=255)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('notification_recipients', models.TextField(blank=True, null=True)),
                ('regular_leave_days', models.IntegerField(default=24)),
                ('carryover_leave_days', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=50)),
                ('sch_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_system.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_system.employeeposition')),
                ('employee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_system.employeetype')),
                ('current_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_system.service')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_system.specialty')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='leave_system.employee'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Υπό Επεξεργασία'), ('APPROVED', 'Εγκρίθηκε'), ('REJECTED', 'Απορρίφθηκε'), ('ISSUED', 'Εκδόθηκε')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('protocol_number', models.CharField(blank=True, max_length=50, null=True)),
                ('kedasy_protocol_number', models.CharField(blank=True, max_length=50, null=True)),
                ('final_signatory', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_decision_text', models.TextField(blank=True, null=True)),
                ('decision_pdf', models.FileField(blank=True, null=True, upload_to='decisions/')),
                ('header_text', models.TextField(blank=True, null=True)),
                ('processed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_by_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave_system.employee')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leaves', to='leave_system.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_system.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='leave_system.leaverequest')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_system.service'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('name_in_accusative', 'surname_in_accusative', 'father_name_in_genitive'), name='unique_employee'),
        ),
    ]
